* added support for simulation name in Control * Control creates output directory (using boost) * added check for boost::filesystem in configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -312,7 +312,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC PERL DOXYGEN DOT DOT_PATH HAVE_DOT LATEX LATEX_PATH GENERATE_LATEX GMSH CXXCPP EGREP LIBMESH_PREFIX COMPLEX_PETSC_DIR COMPLEX_PETSC_ARCH SLEPC_DIR BOOST_CXXFLAGS BOOST_REGEX_LIB GSL_CONFIG GSL_LIBS GSL_CFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CC CFLAGS ac_ct_CC PERL DOXYGEN DOT DOT_PATH HAVE_DOT LATEX LATEX_PATH GENERATE_LATEX GMSH CXXCPP EGREP LIBMESH_PREFIX COMPLEX_PETSC_DIR COMPLEX_PETSC_ARCH SLEPC_DIR BOOST_CXXFLAGS BOOST_REGEX_LIB BOOST_FILESYSTEM_LIB GSL_CONFIG GSL_LIBS GSL_CFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -861,6 +861,9 @@ Optional Packages:
   --with-boost-prefix=DIR specify the path to the boost installation
   --with-boost-regex-lib=LIB
                           specify the boost regex library or library extension
+  --with-boost-filesystem-lib=LIB
+                          specify the boost filesystem library or library
+                          extension
   --with-gsl-config=PROG  specify the GSL config script
 
 Some influential environment variables:
@@ -3945,6 +3948,112 @@ echo "$as_me: error: Boost:regex is not available, but it is needed for TiberCAD
    { (exit 1); exit 1; }; }
 fi
 
+# boost filesystem
+echo "$as_me:$LINENO: checking wether Boost::filesystem is available" >&5
+echo $ECHO_N "checking wether Boost::filesystem is available... $ECHO_C" >&6
+if test "${tc_cv_boost_filesystem_lib+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+# Check whether --with-boost-filesystem-lib or --without-boost-filesystem-lib was given.
+if test "${with_boost_filesystem_lib+set}" = set; then
+  withval="$with_boost_filesystem_lib"
+  tc_cv_boost_filesystem_lib="$with_boost_filesystem_lib"
+fi;
+ CXXFLAGS_save=$CXXFLAGS
+ CXXFLAGS=$BOOST_CXXFLAGS
+ LDFLAGS_save=$LDFLAGS
+ if test "x$tc_cv_boost_prefix" != "x"; then
+   tc_boost_libdir="-Wl,-rpath,${tc_cv_boost_prefix}/lib -L${tc_cv_boost_prefix}/lib"
+ fi
+ tc_boost_lib="boost_filesystem-`$CC --version | awk '{ print ; exit}'` boost_filesystem"
+ if test "${tc_cv_boost_filesystem_lib:+set}" == "set"; then
+   tc_boost_lib="boost_filesystem-$tc_cv_boost_filesystem_lib $tc_cv_boost_filesystem_lib $tc_boost_lib"
+ fi
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ for lib in $tc_boost_lib; do
+   LDFLAGS="$tc_boost_libdir -l$lib"
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/filesystem/operations.hpp>
+int
+main ()
+{
+boost::filesystem::path p("configure");
+				    boost::filesystem::exists(p); return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  tc_cv_boost_filesystem_lib="$LDFLAGS"; break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+ done
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ CXXFLAGS=$CXXFLAGS_save
+ LDFLAGS=$LDFLAGS_save
+fi
+echo "$as_me:$LINENO: result: $tc_cv_boost_filesystem_lib" >&5
+echo "${ECHO_T}$tc_cv_boost_filesystem_lib" >&6
+ if test "${tc_cv_boost_filesystem_lib+set}" == "set"; then
+   BOOST_FILESYSTEM_LIB="$tc_cv_boost_filesystem_lib"
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BOOST_FILESYSTEM 1
+_ACEOF
+
+ fi
+
+if test "${tc_cv_boost_filesystem_lib-no}" == "no"; then
+  { echo "$as_me:$LINENO: " >&5
+echo "$as_me: " >&6;}
+  { { echo "$as_me:$LINENO: error: Boost:filesystem is not available, but it is needed for TiberCAD!" >&5
+echo "$as_me: error: Boost:filesystem is not available, but it is needed for TiberCAD!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 # GSL GNU scientific library
 tc_gsl_config="gsl-config"
 
@@ -5581,6 +5690,7 @@ s,@COMPLEX_PETSC_ARCH@,$COMPLEX_PETSC_ARCH,;t t
 s,@SLEPC_DIR@,$SLEPC_DIR,;t t
 s,@BOOST_CXXFLAGS@,$BOOST_CXXFLAGS,;t t
 s,@BOOST_REGEX_LIB@,$BOOST_REGEX_LIB,;t t
+s,@BOOST_FILESYSTEM_LIB@,$BOOST_FILESYSTEM_LIB,;t t
 s,@GSL_CONFIG@,$GSL_CONFIG,;t t
 s,@GSL_LIBS@,$GSL_LIBS,;t t
 s,@GSL_CFLAGS@,$GSL_CFLAGS,;t t
