Some improvements in the compilation scripts

diff --git a/compilation/common.sh.in b/compilation/common.sh.in
--- a/compilation/common.sh.in
+++ b/compilation/common.sh.in
@@ -1,55 +1,10 @@
-
-# load variables
-[ -e site_config.sh ] && . site_config.sh
-
-# top directory
-TOPDIR=${TOPDIR:-"$(dirname `pwd`)"}
-
-# build directory
-BUILDDIR=${BUILDDIR:-"$(dirname `pwd`)/external"}
-
-# SDK directory
-SDKDIR=${SDKDIR:-"$(dirname `pwd`)/SDK"}
-
-# PETSc version
-PETSCVERSION=${PETSCVERSION:-"3.23.3"}
-PETSCPATCHLEVEL=${PETSCPATCHLEVEL:-""}
-SLEPCVERSION=${SLEPCVERSION:-"3.23.1"}
-SLEPCPATCHLEVEL=${SLEPCPATCHLEVEL:-""}
-
-# libMesh version
-LIBMESHVERSION=${LIBMESHVERSION:-"1.8.4"}
-
-# GMSH version
-GMSHVERSION=${GMSHVERSION:-"4.13.1"}
-
-# BOOST version
-BOOSTVERSION=${BOOSTVERSION:-"1_88_0"}
-
-# whether to compile debug mode or not (y/n)
-DEBUG=${DEBUG:-'n'}
-
-
-
-# build shared libs (yes/no)
-shared_libs=${shared_libs:-'n'}
-
-# CUDA
-CUDADIR=${CUDADIR:-'/usr/pack/cudatoolkit-11.4-ma'}
-
-# use MKL (yes/no)
-if [ -n "$MKLDIR" ]; then
-    MKL="y"
+if test -e variables.sh
+then
+  . variables.sh
 else
-  MKL="n"
+  echo "Cannot run build scripts without variables.sh file."
+  exit 1
 fi
-#MKLDIR=${MKLDIR:-"/usr/pack/intel_oneapi-2021-ma/mkl/latest"}
-
-# MPI
-# NOTE: now MPI is necessary, although one might try again without
-#       (for Windows, e.g.)
-MPI=${MPI:-'y'}
-MPIDIR=${MPIDIR:-"/usr/lib/openmpi/"}
 
 target=@host_cpu@-@host_os@
 
