* finished scripts for debian, but not tested yet

diff --git a/misc/debian-4.0/build_libmesh b/misc/debian-4.0/build_libmesh
--- a/misc/debian-4.0/build_libmesh
+++ b/misc/debian-4.0/build_libmesh
@@ -1,28 +1,57 @@
 #!/bin/bash
 
-export PETSC_DIR=`pwd`/../petsc-2.3.3-p8
-export PETSC_ARCH=linux-gnu-opt
+if [ ! -e common.sh ]; then
+  echo "Need configuration file (common.sh)."
+  exit 1
+fi
+
+. common.sh
 
 
-#export CC=gcc-4.1.1
-#export CXX=g++-4.1.1
-#export FC=gfortran-4.1.1
-export FC=g95-0.91
-export F77=$FC
-export F90=$FC
-#export MPICH_F77=$F77
-#export MPICH_F90=$F90
+echo "Compiling libMesh version $LIBMESHVERSION in $BUILDDIR ..."
 
-export CVS_RSH=ssh
+mkdir -p $BUILDDIR
+if [ ! -d $BUILDDIR ]; then
+  echo "Directory $BUILDDIR does not exist."
+  exit 1
+fi
+
+ARCHIVE=libmesh-${LIBMESHVERSION}.tgz
+PATCH=${PWD}/../libmesh.patch
+
+cd $BUILDDIR
+if [ ! -e ${ARCHIVE} ]; then
+  wget http://surfnet.dl.sourceforge.net/sourceforge/libmesh/${ARCHIVE}
+fi
+
+if [ ! -e ${ARCHIVE} ]; then
+  echo "Could not download slepc."
+  exit 1
+fi
+
+tar zxf ${ARCHIVE}
+
+cd libmesh-${LIBMESHVERSION}
+
+if [ -e ${PATCH} ]; then
+  patch -p0 < ${PATCH}
+fi
+
+
+export PETSC_DIR=${BUILDDIR}/petsc-${PETSCVERSION}-${PATCHLEVEL}
 
   
 ./configure --enable-petsc --disable-slepc --disable-complex --disable-periodic --disable-shared
+
 
 # delete the -pedantic flag because it makes problems with mpi
 cp Make.common Make.common.orig
 sed 's/-pedantic//g' Make.common.orig | sed 's/-D_GLIBCXX_DEBUG_PEDANTIC//g' | sed 's/-D_GLIBCXX_DEBUG//g' > Make.common
 
 
-make
-#make METHOD=dbg
+make |tee make_opt.log
+
+if [ $DEBUG == 'y' ]; then
+  make METHOD=dbg |tee make_dbg.log
+fi
 
diff --git a/misc/debian-4.0/build_slepc b/misc/debian-4.0/build_slepc
--- a/misc/debian-4.0/build_slepc
+++ b/misc/debian-4.0/build_slepc
@@ -1,40 +1,67 @@
 #!/bin/bash
 
-## set the compiler and PATH
 
-v=4.1.1
+if [ ! -e common.sh ]; then
+  echo "Need configuration file (common.sh)."
+  exit 1
+fi
 
-#export CC=gcc-$v
-#export CXX=g++-$v
-export F77=g95-0.91
-#export F77=gfortran-$v
-export F90=$F77
-export FC=$F77
-#export MPICH_F90=$F90
-#export MPICH_F77=$F77
+. common.sh
 
 
+echo "Compiling SLEPc version $PETSCVERSION in $BUILDDIR ..."
 
-export PETSC_DIR=`pwd`/../petsc-2.3.3-p8
+mkdir -p $BUILDDIR
+if [ ! -d $BUILDDIR ]; then
+  echo "Directory $BUILDDIR does not exist."
+  exit 1
+fi
 
-export SLEPC_DIR=`pwd`
+ARCHIVE=slepc-${PETSCVERSION}.tgz
+PATCH=slepc_patch_all-${VERSION}
+
+cd $BUILDDIR
+if [ ! -e ${ARCHIVE} ]; then
+  wget http://www.grycap.upv.es/slepc/download/distrib/${ARCHIVE}
+fi
+
+if [ ! -e ${ARCHIVE} ]; then
+  echo "Could not download slepc."
+  exit 1
+fi
+
+tar zxf ${ARCHIVE}
+
+cd slepc-${PETSCVERSION}
+
+wget http://www.grycap.upv.es/slepc/download/patches/${PATCH}
+if [ -e ${PATCH} ]; then
+  patch -p0 < ${PATCH}
+fi
 
 
-#export PETSC_ARCH=linux-gnu-opt
-#./config/configure.py $CONFIGOPTS
-#make > ${PETSC_ARCH}.log
+
+export PETSC_DIR=${BUILDDIR}/petsc-${PETSCVERSION}-${PATCHLEVEL}
+export SLEPC_DIR=${BUILDDIR}/slepc-${PETSCVERSION}
+
+
+export PETSC_ARCH=linux-gnu-opt
+./config/configure.py $CONFIGOPTS
+make |tee ${PETSC_ARCH}.log
 
 
 export PETSC_ARCH=linux-gnu-complex-opt
 ./config/configure.py $CONFIGOPTS
-make > ${PETSC_ARCH}.log
-
-#export PETSC_ARCH=linux-gnu
-#./config/configure.py $CONFIGOPTS
-#make > ${PETSC_ARCH}.log
+make |tee ${PETSC_ARCH}.log
 
 
-#export PETSC_ARCH=linux-gnu-complex
-#./config/configure.py $CONFIGOPTS
-#make > ${PETSC_ARCH}.log
+if [ $DEBUG == 'y' ]; then
+  export PETSC_ARCH=linux-gnu
+  ./config/configure.py $CONFIGOPTS
+  make |tee ${PETSC_ARCH}.log
+
+  export PETSC_ARCH=linux-gnu-complex
+  ./config/configure.py $CONFIGOPTS
+  make |tee ${PETSC_ARCH}.log
+fi
 
